### PR TITLE
[MAIN-2] Add Author and Publisher fields to the Add Book Page

### PR DESCRIPTION
**Pull request by flukekd**
# Pull Request

Story ID: MAIN-2
Title: Add Author and Publisher fields to the Add Book Page
Card URL: https://trello.com/c/hbkzZyE2
Author: @flukekd

### CODE REVIEW

**Comment by flukekd** [comment]
Screen Shot 2023-01-05 at 16 57 30

**Comment by flukekd** [comment]
Screen Shot 2023-01-05 at 16 58 53

**Comment by cuberetry** [comment]
Please screenshot missing foreign key fields

**Review by cuberetry — APPROVED** [review]
lgtm

**Pull request merged**
