### PR TITLE
[MAIN-1] Handle input fields for author and publisher page

### PR DESCRIPTION
**Pull request by flukekd**
# Pull Request

Story ID: MAIN-1
Title: [MAIN-1] Handle input fields for author and publisher page
Card URL: https://trello.com/c/pzcKm2o7
Author: @flukekd

### CODE REVIEW

**Comment by flukekd** [comment]
Author adding page


Screen Shot 2023-01-07 at 14 09 21
Screen Shot 2023-01-07 at 14 09 41

Screen Shot 2023-01-07 at 14 09 33
Screen Shot 2023-01-07 at 14 10 01
Screen Shot 2023-01-07 at 14 10 11
Screen Shot 2023-01-07 at 14 10 24

**Comment by flukekd** [comment]
Publisher adding page
Screen Shot 2023-01-07 at 14 10 54
Screen Shot 2023-01-07 at 14 11 23
Screen Shot 2023-01-07 at 14 11 27

**Comment by flukekd** [comment]
Book adding page
Screen Shot 2023-01-07 at 14 12 19
Screen Shot 2023-01-07 at 14 13 32
Screen Shot 2023-01-07 at 14 14 43
Screen Shot 2023-01-07 at 14 14 47

**Review by cuberetry — APPROVED** [review]
lgtm

**Pull request merged**
